extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/*.bril'
timeout = 15

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "dune exec -- bin/main.exe -O gLICM ",
    "brili -p {args}",
]
