extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "dune exec -- bin/main.exe",
    "brili -p {args}",
]
